##' @title Generate and export highlighted reconstructed linelist
##'
##' @param mcmc_output Samples generated by `chronofix_mcmc_run()`.
##' @param observed_data Original observed data containing the 'id', 'group',
##'  and event columns.
##' @param error_threshold Posterior probability threshold to classify a date
##'  as an error (default 0.5).
##' @param format File format for the corrected linelist. Default xlsx.
##' @param filename Output file path. If NULL, defaults to "chronofix_linelist.xlsx".
##' @param show_p_error Logical. If FALSE (default), posterior probability
##'  columns are hidden in Excel.
##'
##' @return Output line list dataframe with estimated dates in the chosen file
##'  format.
##'
##' @export
##' @import openxlsx
##' @importFrom dplyr case_when
##' @importFrom stats median
##' @importFrom tools file_ext
chronofix_linelist <- function(mcmc_output = NULL,
                               observed_data = NULL,
                               error_threshold = 0.5,
                               format = "xlsx",
                               filename = NULL,
                               show_p_error = FALSE) {
  
  if (missing(mcmc_output)) stop("'mcmc_output' is missing.")
  if (missing(observed_data)) stop("'observed_data' is missing.")
  if (!"group" %in% colnames(observed_data)) {
    stop("No 'group' column found in observed_data")
  }
  format_lower <- tolower(format)
  if (!format_lower %in% c("xlsx", "csv")) {
    stop("The 'format' argument must be either 'xlsx' or 'csv'.")
  }
  # default filename based on format if not provided
  if (is.null(filename)) {
    filename <- paste0("chronofix_linelist.", format_lower)
  }
  # check that filename extension matches the specified format
  file_extension <- tolower(file_ext(filename))
  if (file_extension != format_lower) {
    stop(sprintf(
      "Extension mismatch: 'filename' has extension '.%s' but 'format' is set to '%s'.",
      file_extension, format_lower
    ))
  }
  
  est_dates_flat <- mcmc_output$data$estimated_dates
  error_ind_array <- mcmc_output$data$error_indicators
  
  # convert dates back to numeric to apply the dimensions
  # [individuals, events, iterations, chains]
  est_dates_numeric <- as.numeric(as.Date(est_dates_flat))
  dim(est_dates_numeric) <- dim(error_ind_array)
  
  # calculate posterior summaries - mean/median across iterations and chains 
  # for every individual (dim 1) and event (dim 2)
  prob_error <- apply(error_ind_array, c(1, 2), mean, na.rm = FALSE)
  median_dates_num <- apply(est_dates_numeric, c(1, 2), stats::median)
  
  n_individuals <- dim(error_ind_array)[1]
  n_events <- dim(error_ind_array)[2]
  
  raw_names <- setdiff(colnames(observed_data), c("id", "group"))
  if (length(raw_names) != n_events) {
    stop("Only 'id', 'group' and event date columns can be supplied as observed data")
  }
  # capitalise first letter of event names
  event_names <- paste0(toupper(substr(raw_names, 1, 1)), substring(raw_names, 2))
  
  results_data <- data.frame(ID = seq_len(n_individuals))
  results_data$Group <- observed_data$group
  
  status_matrix <- chronofix_linelist_status_matrix(
    median_dates_num = median_dates_num,
    prob_error = prob_error,
    error_threshold = error_threshold
  )
  
  for (j in seq_len(n_events)) {
    new_date <- as.Date(median_dates_num[, j], origin = "1970-01-01")
    p_err <- prob_error[, j]
    
    results_data[[event_names[j]]] <- new_date
    results_data[[paste0(event_names[j], "_p_error")]] <- round(p_err, 3)
  }
  
  if (!show_p_error) {
    results_data <- results_data[, !grepl("_p_error$", colnames(results_data)), drop = FALSE]
  }
  
  # Export as CSV
  if (tolower(format) == "csv") {
    message("Note: Saving to CSV removes all coloured formatting")
    if (is.null(filename)) filename <- "chronofix_linelist.csv"
    write.csv(results_data, filename, row.names = FALSE)
    message("Saved CSV linelist to ", filename)
    return(invisible(results_data))
  }
  
  # Export as XLSX
  if (tolower(format) == "xlsx") {
    if (is.null(filename)) filename <- "chronofix_linelist.xlsx"
    wb <- openxlsx::createWorkbook()
    
    openxlsx::addWorksheet(wb, "Reconstructed Dates")
    openxlsx::writeData(wb, "Reconstructed Dates", results_data)
    
    group_col <- which(colnames(results_data) == "Group")
    openxlsx::setColWidths(wb, "Reconstructed Dates", cols = group_col, widths = 22)
    
    col_struct <- "#D3D3D3"
    col_imputed <- "#A7C1E1"
    col_error <- "#E58782"
    col_potential <- "#FAC898"

    style_structural <- openxlsx::createStyle(fgFill = col_struct)
    style_imputed <- openxlsx::createStyle(fgFill = col_imputed, numFmt = "dd/mm/yyyy")
    style_error <- openxlsx::createStyle(fgFill = col_error, numFmt = "dd/mm/yyyy")
    style_potential <- openxlsx::createStyle(fgFill = col_potential, numFmt = "dd/mm/yyyy")
    
    for (j in seq_len(n_events)) {
      excel_col <- which(colnames(results_data) == event_names[j])
      
      # Dynamically set width for specific event column
      event_width <- max(14, nchar(event_names[j]))
      openxlsx::setColWidths(wb, "Reconstructed Dates", cols = excel_col, widths = event_width)
      
      for (i in seq_len(n_individuals)) {
        status <- status_matrix[i, j]
        excel_row <- i + 1
        
        if (!is.na(status)) {
          if (status == "Structurally Missing") {
            openxlsx::addStyle(wb, "Reconstructed Dates", style = style_structural, 
                               rows = excel_row, cols = excel_col)
          } else if (status == "Imputed Missing") {
            openxlsx::addStyle(wb, "Reconstructed Dates", style = style_imputed, 
                               rows = excel_row, cols = excel_col)
          } else if (status == "Error") {
            openxlsx::addStyle(wb, "Reconstructed Dates", style = style_error, 
                               rows = excel_row, cols = excel_col)
          } else if (status == "Potential Error") {
            openxlsx::addStyle(wb, "Reconstructed Dates", style = style_potential, 
                               rows = excel_row, cols = excel_col)
          }
        }
      }
    }
    
    # Add legend tab
    openxlsx::addWorksheet(wb, "Legend")
    
    legend_data <- data.frame(
      Status = c("Correct", "Structurally Missing", "Imputed Missing", "Potential Error", "Error"),
      Description = c(
        "Observed date likely to be correct.",
        "Event did not occur for individuals in this group (not applicable).",
        "Event occurred but date was unrecorded - imputed by model.",
        sprintf("Posterior error probability > 0 but < %s.", error_threshold),
        sprintf("Posterior error probability >= %s. Correct date has been estimated.", error_threshold)
      )
    )
    
    openxlsx::writeData(wb, "Legend", legend_data)
    leg_struct <- openxlsx::createStyle(fgFill = col_struct)
    leg_imputed <- openxlsx::createStyle(fgFill = col_imputed)
    leg_potential <- openxlsx::createStyle(fgFill = col_potential)
    leg_error <- openxlsx::createStyle(fgFill = col_error)
    
    openxlsx::addStyle(wb, "Legend", leg_struct, rows = 3, cols = 1)
    openxlsx::addStyle(wb, "Legend", leg_imputed, rows = 4, cols = 1)
    openxlsx::addStyle(wb, "Legend", leg_potential, rows = 5, cols = 1)
    openxlsx::addStyle(wb, "Legend", leg_error, rows = 6, cols = 1)
    openxlsx::setColWidths(wb, "Legend", cols = 1:2, widths = c(20, 60))
    
    openxlsx::saveWorkbook(wb, filename, overwrite = TRUE)
    message("Saved formatted Excel linelist to ", filename)
    return(invisible(results_data))
  }
  
}

chronofix_linelist_status_matrix <- function(median_dates_num,
                                             prob_error,
                                             error_threshold = 0.5) {
  n_individuals <- nrow(median_dates_num)
  n_events <- ncol(median_dates_num)
  
  status_matrix <- matrix(
    NA_character_,
    nrow = n_individuals,
    ncol = n_events
  )
  
  for (j in seq_len(n_events)) {
    new_date <- as.Date(median_dates_num[, j], origin = "1970-01-01")
    p_err <- prob_error[, j]
    
    status_matrix[, j] <- dplyr::case_when(
      is.na(new_date) ~ "Structurally Missing",
      is.na(p_err) ~ "Imputed Missing",
      p_err >= error_threshold ~ "Error",
      p_err > 0 & p_err < error_threshold ~ "Potential Error",
      TRUE ~ "Correct"
    )
  }
  
  status_matrix
}