##' @title Generate and export highlighted reconstructed linelist
##'
##' @param mcmc_output Samples generated by `chronofix_mcmc_run()`.
##' @param observed_data Original observed data containing the 'id', 'group',
##'  and event columns.
##' @param error_threshold Posterior probability threshold to classify a date
##'  as an error (default 0.5).
##' @param format File format for the corrected linelist. Default xlsx.
##' @param filename Output file path. If NULL, defaults to "chronofix_linelist.xlsx".
##' @param show_p_error Logical. If FALSE (default), posterior probability
##'  columns are hidden in Excel.
##'
##' @return Output line list dataframe with estimated dates in the chosen file
##'  format.
##'
##' @export
##' @import openxlsx
##' @importFrom dplyr case_when
##' @importFrom stats median
##' @importFrom tools file_ext
chronofix_linelist <- function(mcmc_output = NULL,
                               observed_data = NULL,
                               error_threshold = 0.5,
                               format = "xlsx",
                               filename = NULL,
                               show_p_error = FALSE) {
  
  if (missing(mcmc_output)) stop("'mcmc_output' is missing.")
  if (missing(observed_data)) stop("'observed_data' is missing.")
  if (!"group" %in% colnames(observed_data)) {
    stop("No 'group' column found in observed_data")
  }
  format_lower <- tolower(format)
  if (!format_lower %in% c("xlsx", "csv")) {
    stop("The 'format' argument must be either 'xlsx' or 'csv'.")
  }
  # default filename based on format if not provided
  if (is.null(filename)) {
    filename <- paste0("chronofix_linelist.", format_lower)
  }
  # check that filename extension matches the specified format
  file_extension <- tolower(file_ext(filename))
  if (file_extension != format_lower) {
    stop(sprintf(
      "Extension mismatch: 'filename' has extension '.%s' but 'format' is set to '%s'.",
      file_extension, format_lower
    ))
  }
  
  est_dates_flat <- mcmc_output$data$estimated_dates
  error_ind_array <- mcmc_output$data$error_indicators
  
  # convert dates back to numeric to apply the dimensions
  # [individuals, events, iterations, chains]
  est_dates_numeric <- as.numeric(as.Date(est_dates_flat))
  dim(est_dates_numeric) <- dim(error_ind_array)
  
  # calculate posterior summaries - mean across iterations/chains for error
  # and mode across iterations/chains for dates
  prob_error <- apply(error_ind_array, c(1, 2), mean, na.rm = FALSE)
  mode_dates_num <- apply(est_dates_numeric, c(1, 2), get_mode)
  
  n_individuals <- dim(error_ind_array)[1]
  n_events <- dim(error_ind_array)[2]
  
  raw_names <- setdiff(colnames(observed_data), c("id", "group"))
  if (length(raw_names) != n_events) {
    stop("Only 'id', 'group' and event date columns can be supplied as observed data")
  }
  # capitalise first letter of event names
  event_names <- paste0(toupper(substr(raw_names, 1, 1)), substring(raw_names, 2))
  
  results_data <- data.frame(ID = seq_len(n_individuals))
  results_data$Group <- observed_data$group
  
  status_matrix <- chronofix_linelist_status_matrix(
    mode_dates_num = mode_dates_num,
    prob_error = prob_error,
    error_threshold = error_threshold
  )
  
  for (j in seq_len(n_events)) {
    new_date <- as.Date(mode_dates_num[, j], origin = "1970-01-01")
    p_err <- prob_error[, j]
    
    results_data[[event_names[j]]] <- new_date
    results_data[[paste0(event_names[j], "_p_error")]] <- round(p_err, 3)
  }
  
  if (!show_p_error) {
    results_data <- results_data[, !grepl("_p_error$", colnames(results_data)), drop = FALSE]
  }
  
  # Export as CSV
  if (format_lower == "csv") {
    message("Note: Saving to CSV removes all coloured formatting")
    write.csv(results_data, filename, row.names = FALSE)
    message("Saved CSV linelist to ", filename)
    return(invisible(results_data))
  }
  
  # Export as XLSX
  if (format_lower == "xlsx") {
    wb <- openxlsx::createWorkbook()
    
    openxlsx::addWorksheet(wb, "Reconstructed Dates")
    openxlsx::writeData(wb, "Reconstructed Dates", results_data)
    
    group_col <- which(colnames(results_data) == "Group")
    openxlsx::setColWidths(wb, "Reconstructed Dates", cols = group_col, widths = 22)
    
    col_struct <- "#D3D3D3"
    col_imputed <- "#A7C1E1"
    col_error <- "#E58782"
    col_potential <- "#FAC898"

    styles_list <- list(
      style_structural = openxlsx::createStyle(fgFill = col_struct),
      style_imputed    = openxlsx::createStyle(fgFill = col_imputed, numFmt = "dd/mm/yyyy"),
      style_error      = openxlsx::createStyle(fgFill = col_error, numFmt = "dd/mm/yyyy"),
      style_potential  = openxlsx::createStyle(fgFill = col_potential, numFmt = "dd/mm/yyyy")
    )
    
    for (j in seq_len(n_events)) {
      excel_col <- which(colnames(results_data) == event_names[j])
      
      # Dynamically set width for specific event column
      event_width <- max(14, nchar(event_names[j]))
      openxlsx::setColWidths(wb, "Reconstructed Dates", cols = excel_col, widths = event_width)
      
      for (i in seq_len(n_individuals)) {
        status <- status_matrix[i, j]
        excel_row <- i + 1
        
        style_key <- chronofix_style_mapper(status)
        
        if (!is.na(style_key)) {
          openxlsx::addStyle(
            wb, 
            "Reconstructed Dates", 
            style = styles_list[[style_key]], 
            rows = excel_row, 
            cols = excel_col
          )
        }
      }
    }
    
    # Add legend tab
    openxlsx::addWorksheet(wb, "Legend")
    
    legend_data <- data.frame(
      Status = c("Correct", "Structurally Missing", "Imputed Missing", "Potential Error", "Error"),
      Description = c(
        "Observed date likely to be correct and has not been changed.",
        "Event did not occur for individuals in this group (not applicable).",
        "Event occurred but date was unrecorded. Most likely date imputed by model.",
        sprintf("Posterior error probability > 0 but < %s. Observed date has not been changed.", error_threshold),
        sprintf("Posterior error probability >= %s. Most likely correct date has been estimated.", error_threshold)
      )
    )
    
    openxlsx::writeData(wb, "Legend", legend_data)
    leg_struct <- openxlsx::createStyle(fgFill = col_struct)
    leg_imputed <- openxlsx::createStyle(fgFill = col_imputed)
    leg_potential <- openxlsx::createStyle(fgFill = col_potential)
    leg_error <- openxlsx::createStyle(fgFill = col_error)
    
    openxlsx::addStyle(wb, "Legend", leg_struct, rows = 3, cols = 1)
    openxlsx::addStyle(wb, "Legend", leg_imputed, rows = 4, cols = 1)
    openxlsx::addStyle(wb, "Legend", leg_potential, rows = 5, cols = 1)
    openxlsx::addStyle(wb, "Legend", leg_error, rows = 6, cols = 1)
    openxlsx::setColWidths(wb, "Legend", cols = 1:2, widths = c(20, 60))
    
    openxlsx::saveWorkbook(wb, filename, overwrite = TRUE)
    message("Saved formatted Excel linelist to ", filename)
    return(invisible(results_data))
  }
  
}

#' @importFrom stats na.omit
get_mode <- function(x) {
  x <- stats::na.omit(x)
  if (length(x) == 0) return(NA)
  ux <- unique(x)
  ux[which.max(tabulate(match(x, ux)))]
}

#' Helper function to get status matrix
#' @param mode_dates_num numeric matrix of estimated dates (calculated as
#'  posterior modes) for each individual and event.
#' @param prob_error numeric matrix of the posterior error probabilities for
#'  each corresponding date.
#' @param error_threshold numeric cutoff (default 0.5) probabilities greater
#'  than or equal to this are classified as "Error".
chronofix_linelist_status_matrix <- function(mode_dates_num,
                                             prob_error,
                                             error_threshold = 0.5) {
  n_individuals <- nrow(mode_dates_num)
  n_events <- ncol(mode_dates_num)
  
  status_matrix <- matrix(
    NA_character_,
    nrow = n_individuals,
    ncol = n_events
  )
  
  for (j in seq_len(n_events)) {
    new_date <- as.Date(mode_dates_num[, j], origin = "1970-01-01")
    p_err <- prob_error[, j]
    
    status_matrix[, j] <- dplyr::case_when(
      is.na(new_date) ~ "Structurally Missing",
      is.na(p_err) ~ "Imputed Missing",
      p_err >= error_threshold ~ "Error",
      p_err > 0 & p_err < error_threshold ~ "Potential Error",
      TRUE ~ "Correct"
    )
  }
  
  status_matrix
}

#' Helper function to map styles
#' @param status character string for the classification of a date
#'  (e.g., "Error", "Imputed Missing") to be mapped to an Excel style.
chronofix_style_mapper <- function(status) {
  if (is.na(status)) return(NA_character_)
  
  dplyr::case_when(
    status == "Structurally Missing" ~ "style_structural",
    status == "Imputed Missing" ~ "style_imputed",
    status == "Error" ~ "style_error",
    status == "Potential Error" ~ "style_potential",
    TRUE ~ NA_character_
  )
}