##' @title Generate and export highlighted reconstructed linelist
##'
##' @param mcmc_output Samples generated by `chronofix_mcmc_run()`.
##' @param observed_data Original observed data containing the 'id', 'group',
##'  and event columns.
##' @param error_thresholds Numeric vector of length 3, giving the posterior
##'   probability thresholds to classify a date as a possible error 
##'   (default 0.05), likely error (default 0.5) and highly likely error
##'   (default 0.95).
##' @param format File format for the corrected linelist. Default xlsx.
##' @param filename Output file path. If NULL, defaults to "chronofix_linelist.xlsx".
##' @param show_p_error Logical. If FALSE (default), posterior probability
##'  columns are hidden in Excel.
##'
##' @return Output line list dataframe with estimated dates in the chosen file
##'  format.
##'
##' @export
##' @import openxlsx
##' @importFrom dplyr case_when
##' @importFrom stats median
##' @importFrom tools file_ext
chronofix_linelist <- function(mcmc_output = NULL,
                               observed_data = NULL,
                               error_thresholds = c(0.05, 0.5, 0.95),
                               format = "xlsx",
                               filename = NULL,
                               show_p_error = FALSE) {
  
  if (missing(mcmc_output)) stop("'mcmc_output' is missing.")
  if (missing(observed_data)) stop("'observed_data' is missing.")
  if (!"group" %in% colnames(observed_data)) {
    stop("No 'group' column found in observed_data")
  }
  if (!is.numeric(error_thresholds) || length(error_thresholds) != 3) {
    stop("Expected 'error_thresholds' to be a numeric vector of length 3")
  }
  if (any(error_thresholds < 0 | error_thresholds > 1)) {
    stop("Expected all values in 'error_thresholds' to be in the range [0, 1]")
  }
  if (any(diff(error_thresholds) <= 0)) {
    stop("Expected values in 'error_thresholds' to be strictly increasing")
  }
  format_lower <- tolower(format)
  if (!format_lower %in% c("xlsx", "csv")) {
    stop("The 'format' argument must be either 'xlsx' or 'csv'.")
  }
  # default filename based on format if not provided
  if (is.null(filename)) {
    filename <- paste0("chronofix_linelist.", format_lower)
  }
  # check that filename extension matches the specified format
  file_extension <- tolower(file_ext(filename))
  if (file_extension != format_lower) {
    stop(sprintf(
      "Extension mismatch: 'filename' has extension '.%s' but 'format' is set to '%s'.",
      file_extension, format_lower
    ))
  }
  
  est_dates_numeric <- mcmc_output$data$estimated_dates
  error_ind_array <- mcmc_output$data$error_indicators
  
  # calculate posterior summaries - mean across iterations/chains for error
  # and mode across iterations/chains for dates
  # floor applied to convert to corresponding integer for each date
  prob_error <- apply(error_ind_array, c(1, 2), mean, na.rm = FALSE)
  mode_dates_num <- apply(floor(est_dates_numeric), c(1, 2), get_mode)
  
  n_individuals <- dim(error_ind_array)[1]
  n_events <- dim(error_ind_array)[2]
  
  raw_names <- setdiff(colnames(observed_data), c("id", "group"))
  if (length(raw_names) != n_events) {
    stop("Only 'id', 'group' and event date columns can be supplied as observed data")
  }
  # capitalise first letter of event names
  event_names <- paste0(toupper(substr(raw_names, 1, 1)), substring(raw_names, 2))
  
  results_data <- data.frame(ID = observed_data$id)
  results_data$Group <- observed_data$group
  
  status_matrix <- chronofix_linelist_status_matrix(
    mode_dates_num = mode_dates_num,
    prob_error = prob_error,
    error_thresholds = error_thresholds
  )
  
  for (j in seq_len(n_events)) {
    new_date <- as.Date(mode_dates_num[, j], origin = "1970-01-01")
    p_err <- prob_error[, j]
    
    results_data[[event_names[j]]] <- new_date
    results_data[[paste0(event_names[j], "_p_error")]] <- round(p_err, 3)
  }
  
  if (!show_p_error) {
    results_data <- results_data[, !grepl("_p_error$", colnames(results_data)), drop = FALSE]
  }
  
  # Export as CSV
  if (format_lower == "csv") {
    message("Note: Saving to CSV removes all coloured formatting")
    write.csv(results_data, filename, row.names = FALSE)
    message("Saved CSV linelist to ", filename)
    return(invisible(results_data))
  }
  
  # Export as XLSX
  if (format_lower == "xlsx") {
    wb <- openxlsx::createWorkbook()
    
    openxlsx::addWorksheet(wb, "Reconstructed Dates")
    openxlsx::writeData(wb, "Reconstructed Dates", results_data)
    
    group_col <- which(colnames(results_data) == "Group")
    openxlsx::setColWidths(wb, "Reconstructed Dates", cols = group_col, widths = 22)
    
    col_struct <- "#D3D3D3"
    col_imputed <- "#A7C1E1"
    col_highly_likely_error <- "#E58782"
    col_likely_error <- "#FAC898"
    col_possible_error <- "#FCFFCD"

    styles_list <- list(
      style_structural = openxlsx::createStyle(fgFill = col_struct),
      style_imputed    = openxlsx::createStyle(fgFill = col_imputed, 
                                               numFmt = "dd/mm/yyyy"),
      style_highly_likely_error = 
        openxlsx::createStyle(fgFill = col_highly_likely_error, 
                              numFmt = "dd/mm/yyyy"),
      style_likely_error = openxlsx::createStyle(fgFill = col_likely_error,
                                                 numFmt = "dd/mm/yyyy"),
      style_possible_error = openxlsx::createStyle(fgFill = col_possible_error,
                                                   numFmt = "dd/mm/yyyy")
    )
    
    for (j in seq_len(n_events)) {
      excel_col <- which(colnames(results_data) == event_names[j])
      
      # Dynamically set width for specific event column
      event_width <- max(14, nchar(event_names[j]))
      openxlsx::setColWidths(wb, "Reconstructed Dates", cols = excel_col, widths = event_width)
      
      for (i in seq_len(n_individuals)) {
        status <- status_matrix[i, j]
        excel_row <- i + 1
        
        style_key <- chronofix_style_mapper(status)
        
        if (!is.na(style_key)) {
          openxlsx::addStyle(
            wb, 
            "Reconstructed Dates", 
            style = styles_list[[style_key]], 
            rows = excel_row, 
            cols = excel_col
          )
        }
      }
    }
    
    # Add legend tab
    openxlsx::addWorksheet(wb, "Legend")
    
    legend_data <- data.frame(
      Status = c("Correct", "Structurally Missing", "Imputed Missing", "Possible Error", "Likely Error", "Highly Likely Error"),
      Description = c(
        sprintf("Observed date likely to be correct (posterior error probability < %s) and has not been changed.", error_thresholds[1]),
        "Event did not occur for individuals in this group (not applicable).",
        "Event occurred but date was unrecorded. Most likely date imputed by model.",
        sprintf("Posterior error probability >= %s but < %s. Observed date has not been changed.", error_thresholds[1], error_thresholds[2]),
        sprintf("Posterior error probability >= %s but < %s. Observed date has not been changed.", error_thresholds[2], error_thresholds[3]),
        sprintf("Posterior error probability >= %s. Most likely correct date has been estimated.", error_thresholds[3])
      )
    )
    
    openxlsx::writeData(wb, "Legend", legend_data)
    leg_struct <- openxlsx::createStyle(fgFill = col_struct)
    leg_imputed <- openxlsx::createStyle(fgFill = col_imputed)
    leg_possible_error <- openxlsx::createStyle(fgFill = col_possible_error)
    leg_likely_error <- openxlsx::createStyle(fgFill = col_likely_error)
    leg_highly_likely_error <- openxlsx::createStyle(fgFill = col_highly_likely_error)
    
    openxlsx::addStyle(wb, "Legend", leg_struct, rows = 3, cols = 1)
    openxlsx::addStyle(wb, "Legend", leg_imputed, rows = 4, cols = 1)
    openxlsx::addStyle(wb, "Legend", leg_possible_error, rows = 5, cols = 1)
    openxlsx::addStyle(wb, "Legend", leg_likely_error, rows = 6, cols = 1)
    openxlsx::addStyle(wb, "Legend", leg_highly_likely_error, rows = 7, cols = 1)
    openxlsx::setColWidths(wb, "Legend", cols = 1:2, widths = c(20, 60))
    
    openxlsx::saveWorkbook(wb, filename, overwrite = TRUE)
    message("Saved formatted Excel linelist to ", filename)
    return(invisible(results_data))
  }
  
}

#' @importFrom stats na.omit
get_mode <- function(x) {
  x <- stats::na.omit(x)
  if (length(x) == 0) return(NA)
  ux <- unique(x)
  ux[which.max(tabulate(match(x, ux)))]
}


chronofix_linelist_status_matrix <- function(mode_dates_num,
                                             prob_error,
                                             error_thresholds) {
  n_individuals <- nrow(mode_dates_num)
  n_events <- ncol(mode_dates_num)
  
  status_matrix <- matrix(
    NA_character_,
    nrow = n_individuals,
    ncol = n_events
  )
  
  for (j in seq_len(n_events)) {
    new_date <- as.Date(mode_dates_num[, j], origin = "1970-01-01")
    p_err <- prob_error[, j]
    
    status_matrix[, j] <- dplyr::case_when(
      is.na(new_date) ~ "Structurally Missing",
      is.na(p_err) ~ "Imputed Missing",
      p_err >= error_thresholds[1] & p_err < error_thresholds[2] ~ "Possible Error",
      p_err >= error_thresholds[2] & p_err < error_thresholds[3] ~ "Likely Error",
      p_err >= error_thresholds[3] ~ "Highly Likely Error",
      TRUE ~ "Correct"
    )
  }
  
  status_matrix
}


chronofix_style_mapper <- function(status) {
  if (is.na(status)) return(NA_character_)
  
  dplyr::case_when(
    status == "Structurally Missing" ~ "style_structural",
    status == "Imputed Missing" ~ "style_imputed",
    status == "Possible Error" ~ "style_possible_error",
    status == "Likely Error" ~ "style_likely_error",
    status == "Highly Likely Error" ~ "style_highly_likely_error",
    TRUE ~ NA_character_
  )
}
